# Generated by Django 5.1.6 on 2025-03-09 06:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='homefeed',
            name='user_profile',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, related_name='home_feeds', to='Users_app.userprofile'),
            preserve_default=False,
        ),
    ]
