# Generated by Django 5.1.6 on 2025-04-26 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AdventureEvent',
            fields=[
                ('event_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('region', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('activities', models.TextField()),
                ('tourism_impact', models.TextField()),
                ('economic_contribution', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('City_id', models.AutoField(primary_key=True, serialize=False)),
                ('City_name', models.CharField(max_length=100)),
                ('City_code', models.CharField(max_length=10)),
                ('City_population', models.IntegerField()),
                ('city_area', models.FloatField()),
                ('Climate_detail', models.CharField(max_length=200)),
                ('No_of_villages_in_city', models.IntegerField()),
                ('City_description', models.TextField()),
                ('Local_economy', models.CharField(max_length=200)),
                ('is_approved', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='CulturalFestival',
            fields=[
                ('festival_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('location', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('activities', models.TextField()),
                ('season', models.CharField(max_length=255)),
                ('significance', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='District',
            fields=[
                ('District_id', models.AutoField(primary_key=True, serialize=False)),
                ('District_name', models.CharField(max_length=100)),
                ('District_code', models.CharField(max_length=10)),
                ('District_capital_city', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Division',
            fields=[
                ('Division_id', models.AutoField(primary_key=True, serialize=False)),
                ('Division_name', models.CharField(max_length=100)),
                ('Division_code', models.CharField(max_length=10)),
                ('Division_capital_city', models.CharField(max_length=100)),
                ('No_of_districts', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='EmergencyContact',
            fields=[
                ('emergency_contact_id', models.AutoField(primary_key=True, serialize=False)),
                ('government_contact_number', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='FireStation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact_number', models.CharField(max_length=255)),
                ('address', models.CharField()),
                ('operating_hours', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='FolkFestival',
            fields=[
                ('festival_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('region', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('activities', models.TextField()),
                ('economic_impact', models.TextField()),
                ('cultural_relevance', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='GlobalEvent',
            fields=[
                ('event_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('cultural_adaptations', models.TextField()),
                ('activities', models.TextField()),
                ('demographic_participation', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='MedicalEmergency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ambulance_service', models.CharField(max_length=255)),
                ('hospital_emergency_number', models.CharField(max_length=255)),
                ('blood_bank', models.TextField()),
                ('disaster_management', models.TextField()),
                ('contact_for_floods_hazards', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='NationalEvent',
            fields=[
                ('event_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('date', models.DateField()),
                ('description', models.TextField()),
                ('celebrations', models.TextField()),
                ('historical_significance', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='PoliceStation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact_number', models.CharField(max_length=255)),
                ('address', models.CharField()),
                ('operating_hours', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='province',
            fields=[
                ('provinces_id', models.IntegerField(primary_key=True, serialize=False)),
                ('provinces_name', models.CharField(max_length=100)),
                ('provinces_code', models.CharField(max_length=100)),
                ('provinces_capital_city', models.CharField(max_length=100)),
                ('No_divisions_in_provinces', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='RegionalEvent',
            fields=[
                ('event_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('region', models.CharField(max_length=255)),
                ('overview', models.TextField()),
                ('activities', models.TextField()),
                ('significance', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='RegionEvent',
            fields=[
                ('region_id', models.AutoField(primary_key=True, serialize=False)),
                ('region_name', models.CharField(max_length=255)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='ReligiousFestival',
            fields=[
                ('festival_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('traditions', models.TextField()),
                ('significance', models.TextField()),
                ('date', models.DateField()),
                ('associated_rituals', models.TextField()),
            ],
        ),
    ]
