# Generated by Django 5.1.6 on 2025-04-26 10:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Citys_app', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='city',
            name='submitted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='submitted_cities', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='city',
            name='District',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cities', to='Citys_app.district'),
        ),
        migrations.AddField(
            model_name='district',
            name='Division',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='districts', to='Citys_app.division'),
        ),
        migrations.AddField(
            model_name='emergencycontact',
            name='city_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emergency_contacts', to='Citys_app.city'),
        ),
        migrations.AddField(
            model_name='firestation',
            name='emergency_contact',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fire_stations', to='Citys_app.emergencycontact'),
        ),
        migrations.AddField(
            model_name='medicalemergency',
            name='emergency_contact',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medical_emergencies', to='Citys_app.emergencycontact'),
        ),
        migrations.AddField(
            model_name='policestation',
            name='emergency_contact',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='police_stations', to='Citys_app.emergencycontact'),
        ),
        migrations.AddField(
            model_name='division',
            name='Province_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Division', to='Citys_app.province'),
        ),
        migrations.AddField(
            model_name='regionevent',
            name='city_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='region_evevnts', to='Citys_app.city'),
        ),
        migrations.AddField(
            model_name='regionalevent',
            name='region_event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='regional_events', to='Citys_app.regionevent'),
        ),
        migrations.AddField(
            model_name='nationalevent',
            name='region_event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='national_events', to='Citys_app.regionevent'),
        ),
        migrations.AddField(
            model_name='globalevent',
            name='region_event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='global_events', to='Citys_app.regionevent'),
        ),
        migrations.AddField(
            model_name='folkfestival',
            name='region_event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='folk_festivals', to='Citys_app.regionevent'),
        ),
        migrations.AddField(
            model_name='culturalfestival',
            name='region_event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cultural_festivals', to='Citys_app.regionevent'),
        ),
        migrations.AddField(
            model_name='adventureevent',
            name='region_event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='adventure_events', to='Citys_app.regionevent'),
        ),
        migrations.AddField(
            model_name='religiousfestival',
            name='region_event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='religious_festivals', to='Citys_app.regionevent'),
        ),
    ]
