# Generated by Django 5.1.6 on 2025-04-26 11:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Citys_app', '0003_regionevent_created_by_regionevent_is_approved'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='regionevent',
            name='created_by',
        ),
        migrations.AddField(
            model_name='regionevent',
            name='submitted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='submitted_region_events', to=settings.AUTH_USER_MODEL),
        ),
    ]
