# Generated by Django 5.1.6 on 2025-04-27 07:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Citys_app', '0005_religiousfestival_is_approved_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='culturalfestival',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='culturalfestival',
            name='submitted_by',
            field=models.ForeignKey(default=False, on_delete=django.db.models.deletion.CASCADE, related_name='cultural_festivals', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
