# Generated by Django 5.1.6 on 2025-04-27 08:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Citys_app', '0007_folkfestival_is_approved_folkfestival_submitted_by'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='adventureevent',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='adventureevent',
            name='submitted_by',
            field=models.ForeignKey(default=False, on_delete=django.db.models.deletion.CASCADE, related_name='adventure_events', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='emergencycontact',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='emergencycontact',
            name='submitted_by',
            field=models.ForeignKey(default=False, on_delete=django.db.models.deletion.CASCADE, related_name='emergency_contacts', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='firestation',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='firestation',
            name='submitted_by',
            field=models.ForeignKey(default=False, on_delete=django.db.models.deletion.CASCADE, related_name='fire_stations', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='globalevent',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='globalevent',
            name='submitted_by',
            field=models.ForeignKey(default=False, on_delete=django.db.models.deletion.CASCADE, related_name='global_events', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='medicalemergency',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='medicalemergency',
            name='submitted_by',
            field=models.ForeignKey(default=False, on_delete=django.db.models.deletion.CASCADE, related_name='medical_emergencies', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='nationalevent',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='nationalevent',
            name='submitted_by',
            field=models.ForeignKey(default=False, on_delete=django.db.models.deletion.CASCADE, related_name='national_events', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='policestation',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='policestation',
            name='submitted_by',
            field=models.ForeignKey(default=False, on_delete=django.db.models.deletion.CASCADE, related_name='police_stations', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='regionalevent',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='regionalevent',
            name='submitted_by',
            field=models.ForeignKey(default=False, on_delete=django.db.models.deletion.CASCADE, related_name='regional_events', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
