# Generated by Django 5.1.6 on 2025-05-04 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Citys_app', '0008_adventureevent_is_approved_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='city',
            name='emergencyNumber',
            field=models.CharField(default=2, max_length=50),
            preserve_default=False,
        ),
    ]
