# Generated by Django 5.1.6 on 2025-05-04 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Citys_app', '0009_city_emergencynumber'),
    ]

    operations = [
        migrations.AlterField(
            model_name='city',
            name='city_area',
            field=models.CharField(max_length=100),
        ),
    ]
